/*
 * claim_audit.c -- turn "licensed by construction" into "falsified and survived".
 *
 * Every authored coach phrase is a sentence a human wrote; its licence is that
 * its corpus SIGNATURE (gnubg I_* deltas between two post-move boards) is what
 * makes it fire. That licence has been checked by reading. This harness checks
 * it by MEASUREMENT: over thousands of real candidate pairs generated by
 * gnubg's own FindnSaveBestMoves, it dumps, for every (played, variant) pair,
 *
 *   - both boards' full input vectors, in the SAME frame the app uses
 *     (CalculateHalfInputs(anBoard[0],anBoard[1]) = "opp" half first, then
 *     "me" -- identical to gnubg_mobile_position_features),
 *   - pip counts and position class (the matcher's other gates),
 *   - and CLAIM FACTS counted directly off the boards: made home points,
 *     checkers on the bar, blots, anchors in the opponent's home board,
 *     rearmost point. These are what the SENTENCES assert.
 *
 * The auditor (audit.py) then replays the corpus signature logic, and for every
 * firing asserts the sentence's literal claim against those facts. A single
 * counterexample is a defect: the phrase fired where its words were not true.
 *
 * GPLv3+ like the tree.
 *
 * Usage: claim_audit <weights> <positions> <seed>
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "config.h"
#include "eval.h"
#include "positionid.h"

/* ---- claim facts, counted off a TanBoard in the app's frame -------------
 * anBoard[1] = the side that just moved ("me" in corpus terms),
 * anBoard[0] = the opponent ("opp"). Indices 0..23 are points, 24 the bar.
 * "My home board" is my points 1..6 = indices 0..5. The opponent's home
 * board, seen from me, is indices 18..23 (where my anchors live).        */
typedef struct {
    int me_home_points;     /* my made points (>=2) in my home board  */
    int opp_home_points;    /* the opponent's made points in theirs   */
    int me_bar, opp_bar;    /* checkers on the bar                    */
    int me_blots;           /* my points holding exactly one checker  */
    int me_anchors_opp;     /* my made points inside 18..23           */
    int me_rear_anchor;     /* highest index with >=2, else -1        */
    int me_fwd_anchor;      /* MOST ADVANCED anchor in 18..23 (lowest
                             * index), else -1 -- what I_FORWARD_ANCHOR
                             * actually scans (eval.c:844-861)        */
    int me_rear_checker;    /* highest index with >=1, else -1        */
} Facts;

static void facts_of(const TanBoard b, Facts *f)
{
    memset(f, 0, sizeof(*f));
    f->me_rear_anchor = -1;
    f->me_rear_checker = -1;
    f->me_fwd_anchor = -1;
    for (int j = 18; j <= 23; j++) if (b[1][j] >= 2) { f->me_fwd_anchor = j; break; }
    for (int i = 0; i < 6; i++) {
        if (b[1][i] >= 2) f->me_home_points++;
        if (b[0][i] >= 2) f->opp_home_points++;
    }
    for (int i = 0; i < 24; i++) {
        if (b[1][i] == 1) f->me_blots++;
        if (b[1][i] >= 2) {
            f->me_rear_anchor = i;
            if (i >= 18) f->me_anchors_opp++;
        }
        if (b[1][i] >= 1) f->me_rear_checker = i;
    }
    f->me_bar = b[1][24];
    f->opp_bar = b[0][24];
}

static void emit_board(FILE *out, const TanBoard b)
{
    float in[2 * MORE_INPUTS];
    CalculateHalfInputs(b[0], b[1], in);                 /* "opp" half */
    CalculateHalfInputs(b[1], b[0], in + MORE_INPUTS);   /* "me"  half */
    for (int i = 0; i < 2 * MORE_INPUTS; i++) fprintf(out, "\t%.6f", in[i]);

    unsigned int pip[2];
    PipCount((ConstTanBoard) b, pip);
    /* the matcher's PipCount.opp is pips[0] = side 0 = opp */
    fprintf(out, "\t%u\t%u", pip[0], pip[1]);
    fprintf(out, "\t%d", ClassifyPosition((ConstTanBoard) b, VARIATION_STANDARD));

    Facts f; facts_of(b, &f);
    fprintf(out, "\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d",
            f.me_home_points, f.opp_home_points, f.me_bar, f.opp_bar,
            f.me_blots, f.me_anchors_opp, f.me_rear_anchor, f.me_rear_checker,
            f.me_fwd_anchor);
}

int main(int argc, char **argv)
{
    if (argc < 4) {
        fprintf(stderr, "usage: %s <weights> <positions> <seed>\n", argv[0]);
        return 2;
    }
    EvalInitialise(argv[1], NULL, 0, NULL);
    int npos = atoi(argv[2]);
    unsigned int seed = (unsigned int) atoi(argv[3]);
    srandom(seed);

    cubeinfo ci; SetCubeInfoMoney(&ci, 1, 0, 0, FALSE, FALSE, VARIATION_STANDARD);
    movefilter aamf[MAX_FILTER_PLIES][MAX_FILTER_PLIES];
    memcpy(aamf, defaultFilters, sizeof(aamf));
    evalcontext ec = { .fCubeful = FALSE, .nPlies = 0, .fUsePrune = FALSE,
                       .fDeterministic = TRUE, .rNoise = 0.0f };

    TanBoard cur; memset(cur, 0, sizeof(cur));
    int od[26] = {0,-2,0,0,0,0,5,0,3,0,0,0,-5,5,0,0,0,-3,0,-5,0,0,0,0,2,0};
    for (int i = 0; i < 24; i++) {
        int v = od[i + 1];
        if (v > 0) cur[0][i] = v; else if (v < 0) cur[1][23 - i] = -v;
    }
    SwapSides(cur);   /* anBoard[1] = side to move */

    /* header */
    printf("pos\trankV\trankP\teqV\teqP");
    for (int side = 0; side < 2; side++)
        for (int i = 0; i < 2 * MORE_INPUTS; i++)
            printf("\t%c_in%d", side ? 'P' : 'V', i);
    printf("\tV_pip0\tV_pip1\tV_cls\tV_mehome\tV_opphome\tV_mebar\tV_oppbar"
           "\tV_meblots\tV_meanch\tV_rearanch\tV_rearchk\tV_fwdanch");
    printf("\tP_pip0\tP_pip1\tP_cls\tP_mehome\tP_opphome\tP_mebar\tP_oppbar"
           "\tP_meblots\tP_meanch\tP_rearanch\tP_rearchk\tP_fwdanch\n");

    int emitted = 0;
    for (int p = 0; p < npos; p++) {
        /* Stay inside the corpus's domain -- contact play. Beyond it the
         * evaluator wants bearoff databases this harness does not load, and
         * the coach's authored phrases have nothing to say there anyway. */
        int cls_now = ClassifyPosition((ConstTanBoard) cur, VARIATION_STANDARD);
        if (cls_now != CLASS_CONTACT && cls_now != CLASS_CRASHED) {
            memset(cur, 0, sizeof(cur));
            for (int i = 0; i < 24; i++) {
                int v = od[i + 1];
                if (v > 0) cur[0][i] = v; else if (v < 0) cur[1][23 - i] = -v;
            }
            SwapSides(cur);
            /* fresh opening: vary it so the walk does not repeat one game */
            for (int w = 0; w < (int)(random() % 3); w++) { }
        }
        int d0 = 1 + random() % 6, d1 = 1 + random() % 6;
        movelist ml;
        if (FindnSaveBestMoves(&ml, d0, d1, (ConstTanBoard) cur, NULL, TRUE,
                               0.0f, &ci, &ec, aamf) < 0) break;
        if (ml.cMoves < 1) { SwapSides(cur); continue; }

        int k = ml.cMoves < 5 ? ml.cMoves : 5;
        /* every ordered pair (better variant V, worse played P) -- exactly the
         * pairs the coach panel can put on screen */
        for (int iv = 0; iv < k; iv++) {
            for (int ip = iv + 1; ip < k; ip++) {
                TanBoard bv, bp;
                memcpy(bv, cur, sizeof(TanBoard));
                memcpy(bp, cur, sizeof(TanBoard));
                ApplyMove(bv, ml.amMoves[iv].anMove, FALSE);
                ApplyMove(bp, ml.amMoves[ip].anMove, FALSE);
                printf("%d\t%d\t%d\t%.6f\t%.6f", p, iv, ip,
                       ml.amMoves[iv].rScore, ml.amMoves[ip].rScore);
                emit_board(stdout, (ConstTanBoard) bv);
                emit_board(stdout, (ConstTanBoard) bp);
                printf("\n");
                emitted++;
            }
        }
        /* walk on: play the best move, hand the dice over */
        ApplyMove(cur, ml.amMoves[0].anMove, FALSE);
        SwapSides(cur);
        /* restart from the opening if the game ended */
        int off0 = 15, off1 = 15;
        for (int i = 0; i < 25; i++) { off0 -= cur[0][i]; off1 -= cur[1][i]; }
        if (off0 >= 15 || off1 >= 15) {
            memset(cur, 0, sizeof(cur));
            for (int i = 0; i < 24; i++) {
                int v = od[i + 1];
                if (v > 0) cur[0][i] = v; else if (v < 0) cur[1][23 - i] = -v;
            }
            SwapSides(cur);
        }
    }
    fprintf(stderr, "emitted %d pairs from %d positions\n", emitted, npos);
    return 0;
}
